server:
  port : 9191

spring:

  #  to save remember me cookie in db
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1

variables:
  currencyFrom: RUB
  currencyTo: USD
  keyWord: GRIND
