spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parts_store

springdoc:
  api-docs:
    path: /docs/v3/api-docs

variables:
  currencyFrom: RUB
  currencyTo: USD
  keyWord: GRIND
